//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        public int Номер { get; set; }
        public int Объем_продукции { get; set; }
        public System.DateTime Дата_сбора { get; set; }
        public int Номер_участка { get; set; }
        public string Название_продукта { get; set; }
        public System.DateTime Срок_годности { get; set; }
        public System.DateTime Дата_производства { get; set; }
        public bool Тип_животноводческая_растительная_ { get; set; }
        public int Сорт_продукции { get; set; }
        public decimal Стоимость { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Участок Участок { get; set; }
    }
}
