//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Продукция = new HashSet<Продукция>();
        }
    
        public int Статус_оплаты { get; set; }
        public string Отзыв { get; set; }
        public int Тип_заказа { get; set; }
        public int Номер { get; set; }
        public string Паспорт_заказчика { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public decimal Суммарная_стоимость { get; set; }
        public int Колличество { get; set; }
        public string ФИО_заказчика { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продукция> Продукция { get; set; }
    }
}
