//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Обработка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Обработка()
        {
            this.Обслуживающий_персонал = new HashSet<Обслуживающий_персонал>();
        }
    
        public int ID_процесса_обработки { get; set; }
        public System.DateTime Время_обработки { get; set; }
        public int Статус_выполнения { get; set; }
        public int Номер_участка { get; set; }
        public string Описание_процесса_обработки { get; set; }
    
        public virtual Участок Участок { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Обслуживающий_персонал> Обслуживающий_персонал { get; set; }
    }
}
