//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Участок
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Участок()
        {
            this.Замеры = new HashSet<Замеры>();
            this.Обработка = new HashSet<Обработка>();
            this.Продукция = new HashSet<Продукция>();
        }
    
        public int Номер_участка { get; set; }
        public int Площадь { get; set; }
        public int Эффективность { get; set; }
        public string Тип_участка { get; set; }
    
        public virtual Загоны Загоны { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Замеры> Замеры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Обработка> Обработка { get; set; }
        public virtual Поля_и_теплицы Поля_и_теплицы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продукция> Продукция { get; set; }
    }
}
